language: go

go:
  - 1.20.x

# 执行测试
script:
  - go test -v ./...

# 缓存依赖项，加快构建速度
cache:
  directories:
    - $GOPATH/pkg/mod

# 指定分支
branches:
  only:
    - main

# 通知设置
notifications:
  email:
    recipients:
      - collin@nb.cx
    on_success: change
    on_failure: always
